/*
 * Copyright 2012 OneCalendar
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by CoffeeScript 1.3.3
(function() {

  describe('icon help interaction', function() {
    beforeEach(function() {
      return setFixtures("<a class='ablock'></a><div class='help'></div>");
    });
    it("a block that handle help, handle mouse event", function() {
      document.handleHelp('.ablock', '.help', 'my help message');
      expect($(".ablock")).toHandle("mouseover");
      return expect($(".ablock")).toHandle("mouseout");
    });
    it("on mouse over, the help message is displayed", function() {
      document.handleHelp('.ablock', '.help', 'my help message');
      $(".ablock").mouseover();
      return expect($('.help')).toHaveText("my help message");
    });
    return it("on mouse out, the help message go back branck", function() {
      document.handleHelp('.ablock', '.help', 'my help message');
      $(".ablock").mouseout();
      return expect($('.help')).toHaveText("");
    });
  });

}).call(this);
