// Generated by CoffeeScript 1.3.3
(function() {

  describe('icon help interaction', function() {
    beforeEach(function() {
      return setFixtures("<a class='ablock'></a><div class='help'></div>");
    });
    it("a block that handle help, handle mouse event", function() {
      document.handleHelp('.ablock', '.help', 'my help message');
      expect($(".ablock")).toHandle("mouseover");
      return expect($(".ablock")).toHandle("mouseout");
    });
    it("on mouse over, the help message is displayed", function() {
      document.handleHelp('.ablock', '.help', 'my help message');
      $(".ablock").mouseover();
      return expect($('.help')).toHaveText("my help message");
    });
    return it("on mouse out, the help message go back branck", function() {
      document.handleHelp('.ablock', '.help', 'my help message');
      $(".ablock").mouseout();
      return expect($('.help')).toHaveText("");
    });
  });

}).call(this);
